### ISSUE TITLE
List/Detail views for tracks and segments

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/smb-app#13]
### Tracks list activity

Show the user's tracks, ordered by descending datetime. I would use a card view to show basic info about the track (at least start/end date time) and maybe the transport modes (icons) used along the track.

### Track Detail activity

The activity will show the map with the (vector) segments composeing the track overlaid on an OSM base layer.
Beneath the map a list of details about the track:

 - start datetime
 - end datetime
 - types of vehicles
 - calculated values (emissions, costs, healt indexes)

**Comment by offtherailz** [comment]
Just to take note: 
I see an history in this PR https://github.com/geosolutions-it/smb-portal/pull/137 
Different segments can be shown in a list like this.
https://stackoverflow.com/questions/44936373/how-to-create-android-timeline-view-like-google-location-history.
For the moment we show only Start time / end, tyhpes of veichles and calculated values.

**Comment by giohappy** [comment]
Well, it would be great to have a view like that @offtherailz . It depends on how much it would take to implement it. We haven't much budget left for this project. 
If you have an estimate tell us.

**Comment by offtherailz** [comment]
I don't, I worked on it not to much, so I can't estimate it with the correct precision. I was looking otherwise to this issue with @Gnafu and I noticed that there is an hidden issue concerning the id of the track and the rest services present. 
We don't have the same ID for local session and remote id, so we can not connect them. Let's discuss this.
