### ISSUE TITLE
Refresh the access token when expires

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/smb-app#15]
The token expires every 5 minutes

One option is to check the "exp" value of the jwt before making requests and get a new one if expired.

**Comment by offtherailz** [comment]
Other issues concerning the login (most probably on the client side: 

Issue 1: 
0 the session has expired. You are not notified, so you disconnect, and click again on "connect" to re-do the login. 
1 the login is prompted again
2 you do the login 
3 you continue using the same token
Other times :
1 you disconnect 
2 you're not able to do the login again because it is done automatically

**Comment by offtherailz** [comment]
Now we invalidated the token on logout, so this can be closed.
